# This file is auto-generated from the current state of the database. Instead of editing this file, 
# please use the migrations feature of Active Record to incrementally modify your database, and
# then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your database schema. If you need
# to create the application database on another system, you should be using db:schema:load, not running
# all the migrations from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended to check this file into your version control system.

ActiveRecord::Schema.define(:version => 20110122102650) do

  create_table "accounts", :force => true do |t|
    t.string   "account"
    t.string   "passwd"
    t.integer  "is_group"
    t.integer  "run_id"
    t.datetime "created_at"
    t.integer  "created_by"
    t.datetime "deleted_at"
    t.integer  "deleted_by"
    t.integer  "count"
    t.datetime "since"
    t.datetime "till"
    t.integer  "parent_run_id"
    t.string   "seq"
    t.text     "fullseq",          :limit => 2147483647
    t.integer  "merged_to"
    t.integer  "split_from"
    t.string   "name"
    t.text     "fullname"
    t.string   "salt"
    t.string   "role"
    t.integer  "user_info_run_id"
    t.text     "fullseq_sub",      :limit => 2147483647
    t.integer  "updated_to"
    t.boolean  "simulation_mode"
  end

  add_index "accounts", ["created_by"], :name => "index_accounts_on_created_by"
  add_index "accounts", ["deleted_by"], :name => "index_accounts_on_deleted_by"
  add_index "accounts", ["name"], :name => "index_accounts_on_name"
  add_index "accounts", ["run_id"], :name => "index_accounts_on_run_id"
  add_index "accounts", ["simulation_mode"], :name => "index_accounts_on_simulation_mode"
  add_index "accounts", ["updated_to"], :name => "index_accounts_on_updated_to"
  add_index "accounts", ["user_info_run_id"], :name => "index_accounts_on_user_info_run_id"

  create_table "answers", :force => true do |t|
    t.integer  "point"
    t.string   "answer"
    t.integer  "questionnaire_run_id"
    t.string   "_old_messageID"
    t.string   "_old_question_seq"
    t.string   "_creater"
    t.integer  "run_id"
    t.datetime "created_at"
    t.integer  "created_by"
    t.datetime "deleted_at"
    t.integer  "deleted_by"
    t.integer  "count"
    t.datetime "since"
    t.datetime "till"
    t.integer  "parent_run_id"
    t.string   "seq"
    t.text     "fullseq",              :limit => 2147483647
    t.integer  "merged_to"
    t.integer  "split_from"
    t.string   "name"
    t.text     "fullname"
    t.text     "fullseq_sub",          :limit => 2147483647
    t.integer  "updated_to"
    t.boolean  "simulation_mode"
  end

  add_index "answers", ["created_by"], :name => "index_answers_on_created_by"
  add_index "answers", ["deleted_by"], :name => "index_answers_on_deleted_by"
  add_index "answers", ["questionnaire_run_id"], :name => "index_answers_on_questionnaire_run_id"
  add_index "answers", ["run_id"], :name => "index_answers_on_run_id"
  add_index "answers", ["simulation_mode"], :name => "index_answers_on_simulation_mode"
  add_index "answers", ["updated_to"], :name => "index_answers_on_updated_to"

  create_table "article_groups", :force => true do |t|
    t.integer  "article_run_id"
    t.integer  "group_run_id"
    t.integer  "run_id"
    t.datetime "created_at"
    t.integer  "created_by"
    t.datetime "deleted_at"
    t.integer  "deleted_by"
    t.integer  "count"
    t.datetime "since"
    t.datetime "till"
    t.integer  "parent_run_id"
    t.string   "seq"
    t.text     "fullseq",         :limit => 2147483647
    t.integer  "merged_to"
    t.integer  "split_from"
    t.string   "name"
    t.text     "fullname"
    t.text     "fullseq_sub",     :limit => 2147483647
    t.integer  "updated_to"
    t.boolean  "simulation_mode"
  end

  add_index "article_groups", ["article_run_id", "group_run_id"], :name => "index_article_groups_on_article_run_id_and_group_run_id"
  add_index "article_groups", ["article_run_id"], :name => "index_article_groups_on_article_run_id"
  add_index "article_groups", ["created_by"], :name => "index_article_groups_on_created_by"
  add_index "article_groups", ["deleted_by"], :name => "index_article_groups_on_deleted_by"
  add_index "article_groups", ["group_run_id"], :name => "index_article_groups_on_group_run_id"
  add_index "article_groups", ["run_id"], :name => "index_article_groups_on_run_id"
  add_index "article_groups", ["simulation_mode"], :name => "index_article_groups_on_simulation_mode"
  add_index "article_groups", ["updated_to"], :name => "index_article_groups_on_updated_to"

  create_table "article_label_names", :force => true do |t|
    t.integer  "user_info_run_id"
    t.integer  "run_id"
    t.integer  "created_by"
    t.integer  "deleted_by"
    t.datetime "created_at"
    t.datetime "since"
    t.datetime "deleted_at"
    t.datetime "till"
    t.string   "seq"
    t.text     "fullseq",          :limit => 2147483647
    t.text     "fullseq_sub",      :limit => 2147483647
    t.string   "name"
    t.string   "fullname"
    t.integer  "updated_to"
    t.boolean  "simulation_mode"
  end

  add_index "article_label_names", ["simulation_mode"], :name => "index_article_label_names_on_simulation_mode"
  add_index "article_label_names", ["updated_to"], :name => "index_article_label_names_on_updated_to"

  create_table "article_people", :force => true do |t|
    t.integer  "article_run_id"
    t.integer  "user_info_run_id"
    t.integer  "run_id"
    t.datetime "created_at"
    t.integer  "created_by"
    t.datetime "deleted_at"
    t.integer  "deleted_by"
    t.integer  "count"
    t.datetime "since"
    t.datetime "till"
    t.integer  "parent_run_id"
    t.string   "seq"
    t.text     "fullseq",          :limit => 2147483647
    t.integer  "merged_to"
    t.integer  "split_from"
    t.string   "name"
    t.text     "fullname"
    t.text     "fullseq_sub",      :limit => 2147483647
    t.integer  "person_run_id"
    t.integer  "updated_to"
    t.boolean  "simulation_mode"
  end

  add_index "article_people", ["article_run_id", "user_info_run_id"], :name => "index_article_people_on_article_run_id_and_user_info_run_id"
  add_index "article_people", ["article_run_id"], :name => "index_article_people_on_article_run_id"
  add_index "article_people", ["created_by"], :name => "index_article_people_on_created_by"
  add_index "article_people", ["deleted_by"], :name => "index_article_people_on_deleted_by"
  add_index "article_people", ["run_id"], :name => "index_article_people_on_run_id"
  add_index "article_people", ["simulation_mode"], :name => "index_article_people_on_simulation_mode"
  add_index "article_people", ["updated_to"], :name => "index_article_people_on_updated_to"
  add_index "article_people", ["user_info_run_id"], :name => "index_article_people_on_user_info_run_id"

  create_table "articles", :force => true do |t|
    t.string   "title"
    t.text     "body",                 :limit => 2147483647
    t.string   "contact_to"
    t.string   "priority"
    t.string   "article_class"
    t.boolean  "is_news"
    t.boolean  "is_general"
    t.datetime "limit"
    t.string   "url"
    t.string   "url_class"
    t.date     "start_date"
    t.date     "end_date"
    t.time     "start_time"
    t.time     "end_time"
    t.integer  "place_run_id"
    t.string   "non_shared_place"
    t.string   "schedule_class"
    t.text     "mail_to",              :limit => 2147483647
    t.text     "mail_bcc",             :limit => 2147483647
    t.text     "mail_cc",              :limit => 2147483647
    t.text     "_old_lectureID2",      :limit => 2147483647
    t.string   "_sender"
    t.string   "_old_to_category"
    t.string   "bannerID"
    t.string   "bannerParent"
    t.integer  "run_id"
    t.datetime "created_at"
    t.integer  "created_by"
    t.datetime "deleted_at"
    t.integer  "deleted_by"
    t.integer  "count"
    t.datetime "since"
    t.datetime "till"
    t.integer  "parent_run_id"
    t.string   "seq"
    t.text     "fullseq",              :limit => 2147483647
    t.integer  "merged_to"
    t.integer  "split_from"
    t.string   "name"
    t.text     "fullname"
    t.string   "sender_name"
    t.string   "to_individuals"
    t.string   "to_groups"
    t.string   "to_orgs"
    t.integer  "forum_run_id"
    t.string   "forum_type"
    t.integer  "thread_run_id"
    t.integer  "schedule_day_of_week"
    t.text     "fullseq_sub",          :limit => 2147483647
    t.string   "user_category"
    t.integer  "file_attached"
    t.datetime "start_datetime"
    t.datetime "end_datetime"
    t.string   "season"
    t.integer  "banner_run_id"
    t.integer  "banner_part_run_id"
    t.integer  "updated_to"
    t.boolean  "simulation_mode"
  end

  add_index "articles", ["article_class"], :name => "index_articles_on_article_class"
  add_index "articles", ["created_by"], :name => "index_articles_on_created_by"
  add_index "articles", ["deleted_by"], :name => "index_articles_on_deleted_by"
  add_index "articles", ["forum_type", "forum_run_id"], :name => "index_articles_on_forum_type_and_forum_run_id"
  add_index "articles", ["is_general"], :name => "index_articles_on_is_general"
  add_index "articles", ["is_news"], :name => "index_articles_on_is_news"
  add_index "articles", ["parent_run_id"], :name => "index_articles_on_parent_run_id"
  add_index "articles", ["place_run_id"], :name => "index_articles_on_place_run_id"
  add_index "articles", ["run_id", "is_news", "is_general"], :name => "index_articles_on_run_id_and_is_news_and_is_general"
  add_index "articles", ["run_id"], :name => "index_articles_on_run_id"
  add_index "articles", ["schedule_class", "schedule_day_of_week"], :name => "index_articles_on_schedule_class_and_schedule_day_of_week"
  add_index "articles", ["schedule_class"], :name => "index_articles_on_schedule_class"
  add_index "articles", ["schedule_day_of_week"], :name => "index_articles_on_schedule_day_of_week"
  add_index "articles", ["season"], :name => "index_articles_on_season"
  add_index "articles", ["simulation_mode"], :name => "index_articles_on_simulation_mode"
  add_index "articles", ["start_datetime", "end_datetime"], :name => "index_articles_on_start_datetime_and_end_datetime"
  add_index "articles", ["thread_run_id"], :name => "index_articles_on_thread_run_id"
  add_index "articles", ["updated_to"], :name => "index_articles_on_updated_to"

  create_table "attached_files", :force => true do |t|
    t.text     "filename"
    t.text     "original_name",          :limit => 2147483647
    t.text     "directory"
    t.integer  "article_run_id"
    t.integer  "syllabus_run_id"
    t.integer  "exercise_run_id"
    t.integer  "report_run_id"
    t.integer  "user_info_run_id"
    t.integer  "theory_run_id"
    t.integer  "run_id"
    t.datetime "created_at"
    t.integer  "created_by"
    t.datetime "deleted_at"
    t.integer  "deleted_by"
    t.integer  "count"
    t.datetime "since"
    t.datetime "till"
    t.integer  "parent_run_id"
    t.string   "seq"
    t.text     "fullseq",                :limit => 2147483647
    t.integer  "merged_to"
    t.integer  "split_from"
    t.string   "name"
    t.text     "fullname"
    t.integer  "file_attachable_run_id"
    t.string   "file_attachable_type"
    t.text     "fullseq_sub",            :limit => 2147483647
    t.string   "checksum"
    t.integer  "updated_to"
    t.boolean  "simulation_mode"
  end

  add_index "attached_files", ["created_by"], :name => "index_attached_files_on_created_by"
  add_index "attached_files", ["deleted_by"], :name => "index_attached_files_on_deleted_by"
  add_index "attached_files", ["file_attachable_run_id", "file_attachable_type"], :name => "index_attached_files_on_polymorphic"
  add_index "attached_files", ["run_id"], :name => "index_attached_files_on_run_id"
  add_index "attached_files", ["simulation_mode"], :name => "index_attached_files_on_simulation_mode"
  add_index "attached_files", ["updated_to"], :name => "index_attached_files_on_updated_to"

  create_table "bus_diagrams", :force => true do |t|
    t.string   "diagram_type"
    t.string   "holiday"
    t.string   "station"
    t.integer  "hour"
    t.string   "min"
    t.string   "_since"
    t.string   "_till"
    t.integer  "diagram_run_id"
    t.integer  "diagram_type_run_id"
    t.integer  "run_id"
    t.datetime "created_at"
    t.integer  "created_by"
    t.datetime "deleted_at"
    t.integer  "deleted_by"
    t.integer  "count"
    t.datetime "since"
    t.datetime "till"
    t.integer  "parent_run_id"
    t.string   "seq"
    t.text     "fullseq",             :limit => 2147483647
    t.integer  "merged_to"
    t.integer  "split_from"
    t.string   "name"
    t.text     "fullname"
    t.text     "fullseq_sub",         :limit => 2147483647
    t.integer  "updated_to"
    t.boolean  "simulation_mode"
  end

  add_index "bus_diagrams", ["created_by"], :name => "index_bus_diagrams_on_created_by"
  add_index "bus_diagrams", ["deleted_by"], :name => "index_bus_diagrams_on_deleted_by"
  add_index "bus_diagrams", ["diagram_run_id", "diagram_type_run_id"], :name => "index_bus_diagrams_on_diagram_run_id_and_diagram_type_run_id"
  add_index "bus_diagrams", ["diagram_run_id"], :name => "index_bus_diagrams_on_diagram_run_id"
  add_index "bus_diagrams", ["diagram_type"], :name => "index_bus_diagrams_on_diagram_type"
  add_index "bus_diagrams", ["diagram_type_run_id"], :name => "index_bus_diagrams_on_diagram_type_run_id"
  add_index "bus_diagrams", ["holiday"], :name => "index_bus_diagrams_on_holiday"
  add_index "bus_diagrams", ["run_id"], :name => "index_bus_diagrams_on_run_id"
  add_index "bus_diagrams", ["simulation_mode"], :name => "index_bus_diagrams_on_simulation_mode"
  add_index "bus_diagrams", ["station", "holiday", "diagram_type"], :name => "index_bus_diagrams_on_station_and_holiday_and_diagram_type"
  add_index "bus_diagrams", ["station"], :name => "index_bus_diagrams_on_station"
  add_index "bus_diagrams", ["updated_to"], :name => "index_bus_diagrams_on_updated_to"

  create_table "bus_schedules", :force => true do |t|
    t.string   "schedule"
    t.string   "diagram"
    t.string   "holiday"
    t.string   "year"
    t.integer  "diagram_type_run_id"
    t.integer  "run_id"
    t.datetime "created_at"
    t.integer  "created_by"
    t.datetime "deleted_at"
    t.integer  "deleted_by"
    t.integer  "count"
    t.datetime "since"
    t.datetime "till"
    t.integer  "parent_run_id"
    t.string   "seq"
    t.text     "fullseq",             :limit => 2147483647
    t.integer  "merged_to"
    t.integer  "split_from"
    t.string   "name"
    t.text     "fullname"
    t.text     "fullseq_sub",         :limit => 2147483647
    t.integer  "updated_to"
    t.boolean  "simulation_mode"
  end

  add_index "bus_schedules", ["created_by"], :name => "index_bus_schedules_on_created_by"
  add_index "bus_schedules", ["deleted_by"], :name => "index_bus_schedules_on_deleted_by"
  add_index "bus_schedules", ["run_id"], :name => "index_bus_schedules_on_run_id"
  add_index "bus_schedules", ["simulation_mode"], :name => "index_bus_schedules_on_simulation_mode"
  add_index "bus_schedules", ["updated_to"], :name => "index_bus_schedules_on_updated_to"

  create_table "corner_conds", :force => true do |t|
    t.integer  "run_id"
    t.string   "allow"
    t.integer  "corner_run_id"
    t.string   "role"
    t.text     "affiliation_condition", :limit => 2147483647
    t.text     "status_condition",      :limit => 2147483647
    t.string   "name"
    t.integer  "created_by"
    t.integer  "deleted_by"
    t.datetime "created_at"
    t.datetime "since"
    t.datetime "deleted_at"
    t.datetime "till"
    t.string   "seq"
    t.text     "fullseq",               :limit => 2147483647
    t.text     "fullseq_sub",           :limit => 2147483647
    t.string   "fullname"
    t.integer  "merged_to"
    t.integer  "split_from"
    t.integer  "updated_to"
    t.boolean  "simulation_mode"
  end

  add_index "corner_conds", ["corner_run_id"], :name => "index_corner_conds_on_corner_run_id"
  add_index "corner_conds", ["created_by"], :name => "index_corner_conds_on_created_by"
  add_index "corner_conds", ["deleted_by"], :name => "index_corner_conds_on_deleted_by"
  add_index "corner_conds", ["role"], :name => "index_corner_conds_on_role"
  add_index "corner_conds", ["run_id"], :name => "index_corner_conds_on_run_id"
  add_index "corner_conds", ["simulation_mode"], :name => "index_corner_conds_on_simulation_mode"
  add_index "corner_conds", ["updated_to"], :name => "index_corner_conds_on_updated_to"

  create_table "corners", :force => true do |t|
    t.integer  "run_id"
    t.integer  "parent_run_id"
    t.string   "role"
    t.boolean  "logined"
    t.string   "url"
    t.string   "parameters"
    t.boolean  "target_new"
    t.string   "controller"
    t.string   "action"
    t.string   "name"
    t.integer  "created_by"
    t.integer  "deleted_by"
    t.datetime "created_at"
    t.datetime "since"
    t.datetime "deleted_at"
    t.datetime "till"
    t.string   "seq"
    t.text     "fullseq",         :limit => 2147483647
    t.text     "fullseq_sub",     :limit => 2147483647
    t.string   "fullname"
    t.integer  "merged_to"
    t.integer  "split_from"
    t.integer  "updated_to"
    t.boolean  "simulation_mode"
  end

  add_index "corners", ["created_by"], :name => "index_corners_on_created_by"
  add_index "corners", ["deleted_by"], :name => "index_corners_on_deleted_by"
  add_index "corners", ["parent_run_id"], :name => "index_corners_on_parent_run_id"
  add_index "corners", ["run_id"], :name => "index_corners_on_run_id"
  add_index "corners", ["simulation_mode"], :name => "index_corners_on_simulation_mode"
  add_index "corners", ["updated_to"], :name => "index_corners_on_updated_to"

  create_table "course_class_semesters", :force => true do |t|
    t.integer  "run_id"
    t.integer  "course_class_run_id"
    t.string   "semester_run_id"
    t.string   "name"
    t.integer  "created_by"
    t.integer  "deleted_by"
    t.datetime "created_at"
    t.datetime "deleted_at"
    t.datetime "since"
    t.datetime "till"
    t.string   "seq"
    t.text     "fullseq",             :limit => 2147483647
    t.text     "fullseq_sub",         :limit => 2147483647
    t.string   "fullname"
    t.integer  "merged_to"
    t.integer  "split_from"
    t.integer  "updated_to"
    t.boolean  "simulation_mode"
  end

  add_index "course_class_semesters", ["course_class_run_id"], :name => "index_course_class_semesters_on_course_class_run_id"
  add_index "course_class_semesters", ["created_by"], :name => "index_course_class_semesters_on_created_by"
  add_index "course_class_semesters", ["deleted_by"], :name => "index_course_class_semesters_on_deleted_by"
  add_index "course_class_semesters", ["run_id"], :name => "index_course_class_semesters_on_run_id"
  add_index "course_class_semesters", ["semester_run_id"], :name => "index_course_class_semesters_on_semester_run_id"
  add_index "course_class_semesters", ["simulation_mode"], :name => "index_course_class_semesters_on_simulation_mode"
  add_index "course_class_semesters", ["updated_to"], :name => "index_course_class_semesters_on_updated_to"

  create_table "course_classes", :force => true do |t|
    t.string   "_rec_id"
    t.integer  "unit"
    t.string   "office_code"
    t.string   "_affiliation_name"
    t.integer  "organization_run_id"
    t.string   "must_or_choice"
    t.boolean  "is_must"
    t.string   "party"
    t.string   "_subject"
    t.text     "squad_detail",                :limit => 2147483647
    t.string   "teacher_for_math"
    t.boolean  "is_must_for_math_teacher"
    t.string   "teacher_for_info"
    t.boolean  "is_must_for_math_info"
    t.string   "main_or_sub"
    t.boolean  "is_main"
    t.text     "comment",                     :limit => 2147483647
    t.string   "_old_class_id"
    t.integer  "preverse_curriculumn_run_id"
    t.string   "_grade"
    t.string   "_old_subject"
    t.string   "_old_subject_comment"
    t.string   "_old_subject_id"
    t.string   "_class_id"
    t.string   "class_Kei"
    t.string   "class_Gun"
    t.string   "_seq"
    t.string   "_entrance"
    t.string   "division"
    t.string   "_subject_id"
    t.integer  "course_run_id"
    t.string   "open"
    t.integer  "for_web"
    t.string   "rep"
    t.integer  "for_print"
    t.string   "squad_count"
    t.string   "year"
    t.string   "semester"
    t.string   "style"
    t.string   "_TA"
    t.string   "season"
    t.integer  "run_id"
    t.datetime "created_at"
    t.integer  "created_by"
    t.datetime "deleted_at"
    t.integer  "deleted_by"
    t.integer  "count"
    t.datetime "since"
    t.datetime "till"
    t.integer  "parent_run_id"
    t.string   "seq"
    t.text     "fullseq",                     :limit => 2147483647
    t.integer  "merged_to"
    t.integer  "split_from"
    t.string   "name"
    t.text     "fullname"
    t.integer  "status_run_id"
    t.text     "fullseq_sub",                 :limit => 2147483647
    t.string   "_lecture_id"
    t.string   "entMark"
    t.integer  "updated_to"
    t.boolean  "simulation_mode"
  end

  add_index "course_classes", ["course_run_id"], :name => "index_course_classes_on_course_run_id"
  add_index "course_classes", ["created_by"], :name => "index_course_classes_on_created_by"
  add_index "course_classes", ["deleted_by"], :name => "index_course_classes_on_deleted_by"
  add_index "course_classes", ["run_id"], :name => "index_course_classes_on_run_id"
  add_index "course_classes", ["simulation_mode"], :name => "index_course_classes_on_simulation_mode"
  add_index "course_classes", ["updated_to"], :name => "index_course_classes_on_updated_to"

  create_table "courses", :force => true do |t|
    t.integer  "syllabus_run_id"
    t.integer  "previous_course_run_id"
    t.integer  "unit"
    t.boolean  "for_web"
    t.boolean  "for_print"
    t.string   "lecture_type"
    t.integer  "run_id"
    t.datetime "created_at"
    t.integer  "created_by"
    t.text     "create_comment"
    t.datetime "deleted_at"
    t.integer  "deleted_by"
    t.text     "delete_comment"
    t.integer  "version"
    t.integer  "count"
    t.datetime "since"
    t.datetime "till"
    t.integer  "parent_run_id"
    t.integer  "root_run_id"
    t.string   "seq"
    t.text     "fullseq",                :limit => 2147483647
    t.string   "marged_from"
    t.string   "splitted_from"
    t.string   "data_type"
    t.string   "name"
    t.string   "fullname"
    t.text     "fullseq_sub",            :limit => 2147483647
    t.string   "season"
    t.string   "english_name"
    t.string   "subtitle"
    t.string   "year"
    t.integer  "updated_to"
    t.boolean  "simulation_mode"
  end

  add_index "courses", ["created_by"], :name => "index_courses_on_created_by"
  add_index "courses", ["deleted_by"], :name => "index_courses_on_deleted_by"
  add_index "courses", ["run_id", "syllabus_run_id"], :name => "index_courses_on_run_id_and_syllabus_run_id"
  add_index "courses", ["run_id"], :name => "index_courses_on_run_id"
  add_index "courses", ["simulation_mode"], :name => "index_courses_on_simulation_mode"
  add_index "courses", ["syllabus_run_id"], :name => "index_courses_on_syllabus_run_id"
  add_index "courses", ["updated_to"], :name => "index_courses_on_updated_to"

  create_table "destinations", :force => true do |t|
    t.integer  "run_id"
    t.string   "designated_type"
    t.integer  "designated_run_id"
    t.integer  "article_run_id"
    t.string   "type"
    t.text     "description",        :limit => 2147483647
    t.string   "name"
    t.integer  "created_by"
    t.integer  "deleted_by"
    t.datetime "created_at"
    t.datetime "since"
    t.datetime "deleted_at"
    t.datetime "till"
    t.string   "seq"
    t.text     "fullseq",            :limit => 2147483647
    t.text     "fullseq_sub",        :limit => 2147483647
    t.string   "fullname"
    t.integer  "merged_to"
    t.integer  "split_from"
    t.integer  "affiliation_run_id"
    t.integer  "status_run_id"
    t.integer  "original_run_id"
    t.integer  "updated_to"
    t.boolean  "simulation_mode"
  end

  add_index "destinations", ["designated_type", "designated_run_id", "article_run_id", "type"], :name => "index_destinations_on_polymorphic"
  add_index "destinations", ["designated_type", "designated_run_id", "article_run_id"], :name => "index_destinations_on_polymorphic2"
  add_index "destinations", ["designated_type", "designated_run_id"], :name => "index_destinations_on_polymorphic3"
  add_index "destinations", ["run_id"], :name => "index_destinations_on_run_id"
  add_index "destinations", ["simulation_mode"], :name => "index_destinations_on_simulation_mode"
  add_index "destinations", ["type"], :name => "index_destinations_on_type"
  add_index "destinations", ["updated_to"], :name => "index_destinations_on_updated_to"

  create_table "documents", :force => true do |t|
    t.integer  "run_id"
    t.string   "title"
    t.string   "english_title"
    t.string   "authors"
    t.string   "url"
    t.string   "description"
    t.string   "name"
    t.integer  "created_by"
    t.integer  "deleted_by"
    t.datetime "created_at"
    t.datetime "since"
    t.datetime "deleted_at"
    t.datetime "till"
    t.string   "seq"
    t.text     "fullseq",         :limit => 2147483647
    t.text     "fullseq_sub",     :limit => 2147483647
    t.string   "fullname"
    t.integer  "merged_to"
    t.integer  "split_from"
    t.integer  "updated_to"
    t.boolean  "simulation_mode"
  end

  add_index "documents", ["run_id"], :name => "index_papers_on_run_id"
  add_index "documents", ["simulation_mode"], :name => "index_documents_on_simulation_mode"
  add_index "documents", ["updated_to"], :name => "index_documents_on_updated_to"

  create_table "exercises", :force => true do |t|
    t.string   "_old_rec_id"
    t.string   "title"
    t.string   "_old_jujyo_id"
    t.string   "_old_kamoku_id"
    t.integer  "lecture_run_id"
    t.text     "body",            :limit => 2147483647
    t.datetime "limit"
    t.string   "level"
    t.boolean  "is_open"
    t.string   "_creater"
    t.integer  "run_id"
    t.datetime "created_at"
    t.integer  "created_by"
    t.datetime "deleted_at"
    t.integer  "deleted_by"
    t.integer  "count"
    t.datetime "since"
    t.datetime "till"
    t.integer  "parent_run_id"
    t.string   "seq"
    t.text     "fullseq",         :limit => 2147483647
    t.integer  "merged_to"
    t.integer  "split_from"
    t.string   "name"
    t.text     "fullname"
    t.text     "fullseq_sub",     :limit => 2147483647
    t.text     "description"
    t.integer  "updated_to"
    t.boolean  "simulation_mode"
  end

  add_index "exercises", ["created_by"], :name => "index_exercises_on_created_by"
  add_index "exercises", ["deleted_by"], :name => "index_exercises_on_deleted_by"
  add_index "exercises", ["lecture_run_id"], :name => "index_exercises_on_lecture_run_id"
  add_index "exercises", ["run_id"], :name => "index_exercises_on_run_id"
  add_index "exercises", ["simulation_mode"], :name => "index_exercises_on_simulation_mode"
  add_index "exercises", ["updated_to"], :name => "index_exercises_on_updated_to"

  create_table "groups", :force => true do |t|
    t.string   "real_name"
    t.string   "role"
    t.string   "email"
    t.string   "room_no"
    t.string   "room_phone"
    t.text     "url"
    t.integer  "affiliation_run_id"
    t.integer  "status_run_id"
    t.integer  "run_id"
    t.datetime "created_at"
    t.integer  "created_by"
    t.text     "create_comment"
    t.datetime "deleted_at"
    t.integer  "deleted_by"
    t.text     "delete_comment"
    t.integer  "version"
    t.integer  "count"
    t.datetime "since"
    t.datetime "till"
    t.integer  "parent_run_id"
    t.integer  "root_run_id"
    t.string   "seq"
    t.text     "fullseq",            :limit => 2147483647
    t.string   "marged_from"
    t.string   "splitted_from"
    t.string   "data_type"
    t.string   "name"
    t.string   "fullname"
    t.text     "fullseq_sub",        :limit => 2147483647
    t.integer  "updated_to"
    t.boolean  "simulation_mode"
  end

  add_index "groups", ["created_by"], :name => "index_groups_on_created_by"
  add_index "groups", ["deleted_by"], :name => "index_groups_on_deleted_by"
  add_index "groups", ["run_id"], :name => "index_groups_on_run_id"
  add_index "groups", ["simulation_mode"], :name => "index_groups_on_simulation_mode"
  add_index "groups", ["updated_to"], :name => "index_groups_on_updated_to"

  create_table "help_infos", :force => true do |t|
    t.string   "name"
    t.text     "content",         :limit => 2147483647
    t.string   "fullname"
    t.integer  "run_id"
    t.integer  "created_by"
    t.integer  "deleted_by"
    t.datetime "created_at"
    t.datetime "since"
    t.datetime "deleted_at"
    t.datetime "till"
    t.string   "seq"
    t.text     "fullseq",         :limit => 2147483647
    t.text     "fullseq_sub",     :limit => 2147483647
    t.integer  "merged_to"
    t.integer  "split_from"
    t.integer  "updated_to"
    t.boolean  "simulation_mode"
  end

  add_index "help_infos", ["created_by"], :name => "index_help_infos_on_created_by"
  add_index "help_infos", ["deleted_by"], :name => "index_help_infos_on_deleted_by"
  add_index "help_infos", ["name"], :name => "index_help_infos_on_name"
  add_index "help_infos", ["run_id"], :name => "index_help_infos_on_run_id"
  add_index "help_infos", ["simulation_mode"], :name => "index_help_infos_on_simulation_mode"
  add_index "help_infos", ["updated_to"], :name => "index_help_infos_on_updated_to"

  create_table "lecture_course_classes", :force => true do |t|
    t.integer  "run_id"
    t.integer  "lecture_run_id"
    t.integer  "course_class_run_id"
    t.string   "name"
    t.integer  "created_by"
    t.integer  "deleted_by"
    t.datetime "created_at"
    t.datetime "since"
    t.datetime "deleted_at"
    t.datetime "till"
    t.string   "seq"
    t.text     "fullseq",             :limit => 2147483647
    t.text     "fullseq_sub",         :limit => 2147483647
    t.string   "fullname"
    t.integer  "merged_to"
    t.integer  "split_from"
    t.integer  "updated_to"
    t.boolean  "simulation_mode"
  end

  add_index "lecture_course_classes", ["course_class_run_id"], :name => "index_lecture_course_classes_on_course_class_run_id"
  add_index "lecture_course_classes", ["lecture_run_id"], :name => "index_lecture_course_classes_on_lecture_run_id"
  add_index "lecture_course_classes", ["run_id"], :name => "index_lecture_course_classes_on_run_id"
  add_index "lecture_course_classes", ["simulation_mode"], :name => "index_lecture_course_classes_on_simulation_mode"
  add_index "lecture_course_classes", ["updated_to"], :name => "index_lecture_course_classes_on_updated_to"

  create_table "lecture_resources", :force => true do |t|
    t.string   "_old_subject_id"
    t.string   "_old_class_id"
    t.integer  "lecture_run_id"
    t.string   "_old_youbi"
    t.integer  "day_of_week"
    t.string   "_old_jikan"
    t.integer  "lecture_time"
    t.string   "_old_roon"
    t.string   "room"
    t.string   "year"
    t.integer  "run_id"
    t.datetime "created_at"
    t.integer  "created_by"
    t.datetime "deleted_at"
    t.integer  "deleted_by"
    t.integer  "count"
    t.datetime "since"
    t.datetime "till"
    t.integer  "parent_run_id"
    t.string   "seq"
    t.text     "fullseq",         :limit => 2147483647
    t.integer  "merged_to"
    t.integer  "split_from"
    t.string   "name"
    t.text     "fullname"
    t.text     "fullseq_sub",     :limit => 2147483647
    t.integer  "updated_to"
    t.boolean  "simulation_mode"
  end

  add_index "lecture_resources", ["created_by"], :name => "index_lecture_resources_on_created_by"
  add_index "lecture_resources", ["deleted_by"], :name => "index_lecture_resources_on_deleted_by"
  add_index "lecture_resources", ["lecture_run_id"], :name => "index_lecture_resources_on_lecture_run_id"
  add_index "lecture_resources", ["run_id"], :name => "index_lecture_resources_on_run_id"
  add_index "lecture_resources", ["simulation_mode"], :name => "index_lecture_resources_on_simulation_mode"
  add_index "lecture_resources", ["updated_to"], :name => "index_lecture_resources_on_updated_to"

  create_table "lecture_rooms", :force => true do |t|
    t.string   "name"
    t.integer  "lecture_time_run_id"
    t.integer  "space_run_id"
    t.integer  "room_comment"
    t.integer  "run_id"
    t.integer  "created_by"
    t.integer  "deleted_by"
    t.datetime "created_at"
    t.datetime "since"
    t.datetime "deleted_at"
    t.datetime "till"
    t.string   "seq"
    t.text     "fullseq",             :limit => 2147483647
    t.text     "fullseq_sub",         :limit => 2147483647
    t.string   "fullname"
    t.integer  "merged_to"
    t.integer  "split_from"
    t.integer  "updated_to"
    t.boolean  "simulation_mode"
  end

  add_index "lecture_rooms", ["created_by"], :name => "index_lecture_rooms_on_created_by"
  add_index "lecture_rooms", ["deleted_by"], :name => "index_lecture_rooms_on_deleted_by"
  add_index "lecture_rooms", ["lecture_time_run_id", "space_run_id"], :name => "index_lecture_rooms_on_lecture_time_run_id_and_space_run_id"
  add_index "lecture_rooms", ["lecture_time_run_id"], :name => "index_lecture_rooms_on_lecture_time_run_id"
  add_index "lecture_rooms", ["room_comment"], :name => "index_lecture_rooms_on_room_comment"
  add_index "lecture_rooms", ["run_id"], :name => "index_lecture_rooms_on_run_id"
  add_index "lecture_rooms", ["simulation_mode"], :name => "index_lecture_rooms_on_simulation_mode"
  add_index "lecture_rooms", ["space_run_id"], :name => "index_lecture_rooms_on_space_run_id"
  add_index "lecture_rooms", ["updated_to"], :name => "index_lecture_rooms_on_updated_to"

  create_table "lecture_time_to_real_time", :force => true do |t|
    t.integer  "lecture_time"
    t.time     "real_start_time"
    t.time     "real_end_time"
    t.integer  "run_id"
    t.string   "name"
    t.integer  "created_by"
    t.integer  "deleted_by"
    t.datetime "created_at"
    t.datetime "since"
    t.datetime "deleted_at"
    t.datetime "till"
    t.string   "seq"
    t.text     "fullseq",         :limit => 2147483647
    t.text     "fullseq_sub",     :limit => 2147483647
    t.string   "fullname"
    t.integer  "merged_to"
    t.integer  "split_from"
    t.integer  "updated_to"
    t.boolean  "simulation_mode"
  end

  add_index "lecture_time_to_real_time", ["created_by"], :name => "index_lecture_time_to_real_time_on_created_by"
  add_index "lecture_time_to_real_time", ["deleted_by"], :name => "index_lecture_time_to_real_time_on_deleted_by"
  add_index "lecture_time_to_real_time", ["lecture_time"], :name => "index_lecture_time_to_real_time_on_lecture_time"
  add_index "lecture_time_to_real_time", ["real_end_time"], :name => "index_lecture_time_to_real_time_on_real_end_time"
  add_index "lecture_time_to_real_time", ["real_start_time"], :name => "index_lecture_time_to_real_time_on_real_start_time"
  add_index "lecture_time_to_real_time", ["run_id"], :name => "index_lecture_time_to_real_time_on_run_id"
  add_index "lecture_time_to_real_time", ["simulation_mode"], :name => "index_lecture_time_to_real_time_on_simulation_mode"
  add_index "lecture_time_to_real_time", ["updated_to"], :name => "index_lecture_time_to_real_time_on_updated_to"

  create_table "lecture_times", :force => true do |t|
    t.integer  "lecture_run_id"
    t.integer  "day_of_week"
    t.integer  "lecture_time"
    t.integer  "run_id"
    t.integer  "created_by"
    t.integer  "deleted_by"
    t.datetime "created_at"
    t.datetime "since"
    t.datetime "deleted_at"
    t.datetime "till"
    t.string   "seq"
    t.text     "fullseq",         :limit => 2147483647
    t.text     "fullseq_sub",     :limit => 2147483647
    t.string   "name"
    t.string   "fullname"
    t.integer  "merged_to"
    t.integer  "split_from"
    t.string   "season"
    t.string   "room"
    t.integer  "updated_to"
    t.boolean  "simulation_mode"
  end

  add_index "lecture_times", ["created_by"], :name => "index_lecture_times_on_created_by"
  add_index "lecture_times", ["day_of_week", "lecture_time"], :name => "index_lecture_times_on_day_of_week_and_lecture_time"
  add_index "lecture_times", ["day_of_week"], :name => "index_lecture_times_on_day_of_week"
  add_index "lecture_times", ["deleted_by"], :name => "index_lecture_times_on_deleted_by"
  add_index "lecture_times", ["lecture_run_id"], :name => "index_lecture_times_on_lecture_run_id"
  add_index "lecture_times", ["lecture_time"], :name => "index_lecture_times_on_lecture_time"
  add_index "lecture_times", ["run_id"], :name => "index_lecture_times_on_run_id"
  add_index "lecture_times", ["season"], :name => "index_lecture_times_on_season"
  add_index "lecture_times", ["simulation_mode"], :name => "index_lecture_times_on_simulation_mode"
  add_index "lecture_times", ["updated_to"], :name => "index_lecture_times_on_updated_to"

  create_table "lectures", :force => true do |t|
    t.integer  "previous_course_run_id"
    t.integer  "unit"
    t.boolean  "for_web"
    t.boolean  "for_print"
    t.string   "lecture_type"
    t.integer  "run_id"
    t.datetime "created_at"
    t.integer  "created_by"
    t.text     "create_comment"
    t.datetime "deleted_at"
    t.integer  "deleted_by"
    t.text     "delete_comment"
    t.integer  "version"
    t.integer  "count"
    t.datetime "since"
    t.datetime "till"
    t.integer  "parent_run_id"
    t.integer  "root_run_id"
    t.string   "seq"
    t.text     "fullseq",                :limit => 2147483647
    t.string   "marged_from"
    t.string   "splitted_from"
    t.string   "data_type"
    t.string   "name"
    t.string   "fullname"
    t.text     "fullseq_sub",            :limit => 2147483647
    t.integer  "course_run_id"
    t.integer  "syllabus_run_id"
    t.string   "syllabus_name"
    t.integer  "course_class_run_id"
    t.string   "year"
    t.string   "_lecture_id"
    t.integer  "updated_to"
    t.boolean  "simulation_mode"
  end

  add_index "lectures", ["course_run_id"], :name => "index_lectures_on_course_run_id"
  add_index "lectures", ["created_by"], :name => "index_lectures_on_created_by"
  add_index "lectures", ["deleted_by"], :name => "index_lectures_on_deleted_by"
  add_index "lectures", ["run_id", "course_run_id"], :name => "index_lectures_on_run_id_and_course_run_id"
  add_index "lectures", ["run_id", "syllabus_run_id"], :name => "index_lectures_syllabus_run_id"
  add_index "lectures", ["run_id"], :name => "index_lectures_on_run_id"
  add_index "lectures", ["simulation_mode"], :name => "index_lectures_on_simulation_mode"
  add_index "lectures", ["syllabus_run_id"], :name => "index_lectures_on_syllabus_run_id"
  add_index "lectures", ["updated_to"], :name => "index_lectures_on_updated_to"

  create_table "mail_accounts", :force => true do |t|
    t.string   "description"
    t.string   "address"
    t.string   "fullname"
    t.string   "pop_server"
    t.integer  "pop_port"
    t.string   "pop_auth"
    t.string   "pop_username"
    t.string   "pop_password"
    t.string   "smtp_server"
    t.integer  "smtp_port"
    t.string   "smtp_auth"
    t.string   "smtp_username"
    t.string   "smtp_password"
    t.string   "include_account"
    t.boolean  "default"
    t.string   "username"
    t.boolean  "delete_messages"
    t.string   "reply_to"
    t.string   "requires_smtp_auth"
    t.string   "signature"
    t.integer  "run_id"
    t.integer  "user_info_run_id"
    t.string   "name"
    t.integer  "created_by"
    t.integer  "deleted_by"
    t.datetime "created_at"
    t.datetime "since"
    t.datetime "deleted_at"
    t.datetime "till"
    t.string   "seq"
    t.text     "fullseq",            :limit => 2147483647
    t.text     "fullseq_sub",        :limit => 2147483647
    t.integer  "merged_to"
    t.integer  "split_from"
    t.boolean  "pop_ssl_enable"
    t.boolean  "smtp_ssl_enable"
    t.integer  "updated_to"
    t.boolean  "simulation_mode"
  end

  add_index "mail_accounts", ["created_by"], :name => "index_mail_accounts_on_created_by"
  add_index "mail_accounts", ["deleted_by"], :name => "index_mail_accounts_on_deleted_by"
  add_index "mail_accounts", ["run_id"], :name => "index_mail_accounts_on_run_id"
  add_index "mail_accounts", ["simulation_mode"], :name => "index_mail_accounts_on_simulation_mode"
  add_index "mail_accounts", ["updated_to"], :name => "index_mail_accounts_on_updated_to"

  create_table "maintenance_infos", :force => true do |t|
    t.text     "content",         :limit => 2147483647
    t.string   "url"
    t.integer  "run_id"
    t.string   "name"
    t.integer  "created_by"
    t.integer  "deleted_by"
    t.datetime "created_at"
    t.datetime "deleted_at"
    t.datetime "since"
    t.datetime "till"
    t.string   "seq"
    t.text     "fullseq",         :limit => 2147483647
    t.text     "fullseq_sub",     :limit => 2147483647
    t.string   "fullname"
    t.integer  "merged_to"
    t.integer  "split_from"
    t.integer  "updated_to"
    t.boolean  "simulation_mode"
  end

  add_index "maintenance_infos", ["created_by"], :name => "index_maintenance_infos_on_created_by"
  add_index "maintenance_infos", ["deleted_by"], :name => "index_maintenance_infos_on_deleted_by"
  add_index "maintenance_infos", ["run_id"], :name => "index_maintenance_infos_on_run_id"
  add_index "maintenance_infos", ["simulation_mode"], :name => "index_maintenance_infos_on_simulation_mode"
  add_index "maintenance_infos", ["updated_to"], :name => "index_maintenance_infos_on_updated_to"

  create_table "members", :force => true do |t|
    t.integer  "run_id"
    t.string   "memberable_type"
    t.integer  "memberable_run_id"
    t.integer  "user_info_run_id"
    t.string   "type"
    t.string   "description"
    t.boolean  "representative"
    t.integer  "is_accepted"
    t.text     "reason",            :limit => 2147483647
    t.string   "name"
    t.integer  "created_by"
    t.integer  "deleted_by"
    t.datetime "created_at"
    t.datetime "since"
    t.datetime "deleted_at"
    t.datetime "till"
    t.string   "seq"
    t.text     "fullseq",           :limit => 2147483647
    t.text     "fullseq_sub",       :limit => 2147483647
    t.string   "fullname"
    t.integer  "merged_to"
    t.integer  "split_from"
    t.integer  "original_run_id"
    t.boolean  "simulation_mode"
    t.integer  "updated_to"
  end

  add_index "members", ["created_by"], :name => "index_members_on_created_by"
  add_index "members", ["deleted_by"], :name => "index_members_on_deleted_by"
  add_index "members", ["memberable_run_id", "user_info_run_id"], :name => "index_members_on_memberable_run_id_and_user_info_run_id"
  add_index "members", ["memberable_run_id"], :name => "index_members_on_memberable_run_id"
  add_index "members", ["memberable_type", "memberable_run_id", "type", "user_info_run_id"], :name => "index_members_on_polymorphic"
  add_index "members", ["memberable_type", "memberable_run_id", "type"], :name => "index_members_on_polymorphic_withuot_uid"
  add_index "members", ["memberable_type", "memberable_run_id", "user_info_run_id"], :name => "index_members_on_polymorphic_withuot_type"
  add_index "members", ["memberable_type", "memberable_run_id"], :name => "index_members_on_polymorphic_withuot_type_and_uid"
  add_index "members", ["run_id"], :name => "index_members_on_run_id"
  add_index "members", ["simulation_mode"], :name => "index_members_on_simulation_mode"
  add_index "members", ["type"], :name => "index_members_on_type"
  add_index "members", ["updated_to"], :name => "index_members_on_updated_to"
  add_index "members", ["user_info_run_id"], :name => "index_members_on_user_info_run_id"

  create_table "org_dependencies", :force => true do |t|
    t.integer  "affiliation_run_id"
    t.integer  "status_run_id"
    t.boolean  "affiliation_children_follow"
    t.boolean  "status_children_follow"
    t.integer  "run_id"
    t.integer  "created_by"
    t.integer  "deleted_by"
    t.datetime "created_at"
    t.datetime "deleted_at"
    t.datetime "since"
    t.datetime "till"
    t.string   "seq"
    t.text     "fullseq",                     :limit => 2147483647
    t.text     "fullseq_sub",                 :limit => 2147483647
    t.string   "name"
    t.string   "fullname"
    t.integer  "merged_to"
    t.integer  "split_from"
    t.integer  "updated_to"
    t.boolean  "simulation_mode"
  end

  add_index "org_dependencies", ["affiliation_children_follow"], :name => "index_org_dependencies_on_affiliation_children_follow"
  add_index "org_dependencies", ["affiliation_run_id", "status_run_id"], :name => "index_org_dependencies_on_affiliation_run_id_and_status_run_id"
  add_index "org_dependencies", ["affiliation_run_id"], :name => "index_org_dependencies_on_affiliation_run_id"
  add_index "org_dependencies", ["created_by"], :name => "index_org_dependencies_on_created_by"
  add_index "org_dependencies", ["deleted_by"], :name => "index_org_dependencies_on_deleted_by"
  add_index "org_dependencies", ["run_id"], :name => "index_org_dependencies_on_run_id"
  add_index "org_dependencies", ["simulation_mode"], :name => "index_org_dependencies_on_simulation_mode"
  add_index "org_dependencies", ["status_children_follow"], :name => "index_org_dependencies_on_status_children_follow"
  add_index "org_dependencies", ["status_run_id"], :name => "index_org_dependencies_on_status_run_id"
  add_index "org_dependencies", ["updated_to"], :name => "index_org_dependencies_on_updated_to"

  create_table "organizations", :force => true do |t|
    t.integer  "affiliation_run_id"
    t.integer  "status_run_id"
    t.string   "_old_positionID"
    t.string   "_parent"
    t.integer  "organized_entity_run_id"
    t.string   "title"
    t.string   "post"
    t.integer  "run_id"
    t.datetime "created_at"
    t.integer  "created_by"
    t.datetime "deleted_at"
    t.integer  "deleted_by"
    t.integer  "count"
    t.datetime "since"
    t.datetime "till"
    t.integer  "parent_run_id"
    t.string   "seq"
    t.text     "fullseq",                 :limit => 2147483647
    t.integer  "merged_to"
    t.integer  "split_from"
    t.string   "name"
    t.text     "fullname"
    t.string   "organized_entity_type"
    t.text     "fullseq_sub",             :limit => 2147483647
    t.integer  "updated_to"
    t.boolean  "simulation_mode"
    t.text     "party"
  end

  add_index "organizations", ["affiliation_run_id", "status_run_id"], :name => "index_organizations_on_affiliation_run_id_and_status_run_id"
  add_index "organizations", ["affiliation_run_id"], :name => "index_organizations_on_affiliation_run_id"
  add_index "organizations", ["created_by"], :name => "index_organizations_on_created_by"
  add_index "organizations", ["deleted_by"], :name => "index_organizations_on_deleted_by"
  add_index "organizations", ["organized_entity_run_id", "organized_entity_type", "affiliation_run_id", "status_run_id"], :name => "index_organizations_on_polymorphic_and_org"
  add_index "organizations", ["organized_entity_run_id", "organized_entity_type"], :name => "index_organizations_on_polymorphic"
  add_index "organizations", ["run_id"], :name => "index_organizations_on_run_id"
  add_index "organizations", ["simulation_mode"], :name => "index_organizations_on_simulation_mode"
  add_index "organizations", ["status_run_id"], :name => "index_organizations_on_status_run_id"
  add_index "organizations", ["updated_to"], :name => "index_organizations_on_updated_to"

  create_table "password_regists", :force => true do |t|
    t.integer  "account_run_id"
    t.text     "passwd"
    t.text     "code_on_mail"
    t.integer  "run_id"
    t.datetime "created_at"
    t.integer  "created_by"
    t.datetime "deleted_at"
    t.integer  "deleted_by"
    t.integer  "count"
    t.datetime "since"
    t.datetime "till"
    t.integer  "parent_run_id"
    t.string   "seq"
    t.text     "fullseq",         :limit => 2147483647
    t.integer  "merged_to"
    t.integer  "split_from"
    t.string   "name"
    t.text     "fullname"
    t.text     "fullseq_sub",     :limit => 2147483647
    t.string   "salt"
    t.integer  "updated_to"
    t.boolean  "simulation_mode"
  end

  add_index "password_regists", ["account_run_id"], :name => "index_password_regists_on_account_run_id"
  add_index "password_regists", ["created_by"], :name => "index_password_regists_on_created_by"
  add_index "password_regists", ["deleted_by"], :name => "index_password_regists_on_deleted_by"
  add_index "password_regists", ["run_id"], :name => "index_password_regists_on_run_id"
  add_index "password_regists", ["simulation_mode"], :name => "index_password_regists_on_simulation_mode"
  add_index "password_regists", ["updated_to"], :name => "index_password_regists_on_updated_to"

  create_table "personal_configs", :force => true do |t|
    t.integer  "run_id"
    t.integer  "user_info_run_id"
    t.integer  "configurable_run_id"
    t.string   "configurable_type"
    t.string   "name"
    t.string   "value"
    t.string   "description"
    t.integer  "created_by"
    t.integer  "deleted_by"
    t.datetime "created_at"
    t.datetime "since"
    t.datetime "deleted_at"
    t.datetime "till"
    t.string   "seq"
    t.text     "fullseq",             :limit => 2147483647
    t.text     "fullseq_sub",         :limit => 2147483647
    t.string   "fullname"
    t.integer  "merged_to"
    t.integer  "split_from"
    t.integer  "updated_to"
    t.boolean  "simulation_mode"
  end

  add_index "personal_configs", ["configurable_run_id", "configurable_type", "name", "user_info_run_id"], :name => "index_personal_configs_on_polymorphic_and_name_and_uid"
  add_index "personal_configs", ["configurable_run_id", "configurable_type", "name"], :name => "index_personal_configs_on_polymorphic_and_name"
  add_index "personal_configs", ["configurable_run_id", "configurable_type", "user_info_run_id"], :name => "index_personal_configs_on_polymorphic_and_uid"
  add_index "personal_configs", ["configurable_run_id", "configurable_type"], :name => "index_personal_configs_on_polymorphic"
  add_index "personal_configs", ["configurable_run_id"], :name => "index_personal_configs_on_configurable_run_id"
  add_index "personal_configs", ["configurable_type"], :name => "index_personal_configs_on_configurable_type"
  add_index "personal_configs", ["name"], :name => "index_personal_configs_on_name"
  add_index "personal_configs", ["run_id"], :name => "index_personal_configs_on_run_id"
  add_index "personal_configs", ["simulation_mode"], :name => "index_personal_configs_on_simulation_mode"
  add_index "personal_configs", ["updated_to"], :name => "index_personal_configs_on_updated_to"
  add_index "personal_configs", ["user_info_run_id"], :name => "index_personal_configs_on_user_info_run_id"

  create_table "personal_settings", :force => true do |t|
    t.integer  "thread_run_id"
    t.integer  "user_info_run_id"
    t.integer  "run_id"
    t.datetime "created_at"
    t.integer  "created_by"
    t.text     "create_comment"
    t.datetime "deleted_at"
    t.integer  "deleted_by"
    t.text     "delete_comment"
    t.integer  "version"
    t.integer  "count"
    t.datetime "since"
    t.datetime "till"
    t.integer  "parent_run_id"
    t.integer  "root_run_id"
    t.string   "seq"
    t.text     "fullseq",          :limit => 2147483647
    t.string   "marged_from"
    t.string   "splitted_from"
    t.string   "data_type"
    t.string   "name"
    t.string   "fullname"
    t.text     "fullseq_sub",      :limit => 2147483647
    t.integer  "updated_to"
    t.boolean  "simulation_mode"
  end

  add_index "personal_settings", ["created_by"], :name => "index_personal_settings_on_created_by"
  add_index "personal_settings", ["deleted_by"], :name => "index_personal_settings_on_deleted_by"
  add_index "personal_settings", ["name"], :name => "index_personal_settings_on_name"
  add_index "personal_settings", ["run_id"], :name => "index_personal_settings_on_run_id"
  add_index "personal_settings", ["simulation_mode"], :name => "index_personal_settings_on_simulation_mode"
  add_index "personal_settings", ["thread_run_id", "user_info_run_id"], :name => "index_personal_settings_on_thread_run_id_and_user_info_run_id"
  add_index "personal_settings", ["thread_run_id"], :name => "index_personal_settings_on_thread_run_id"
  add_index "personal_settings", ["updated_to"], :name => "index_personal_settings_on_updated_to"
  add_index "personal_settings", ["user_info_run_id"], :name => "index_personal_settings_on_user_info_run_id"

  create_table "positions", :force => true do |t|
    t.string   "_old_positionID"
    t.string   "_parent"
    t.string   "mark"
    t.string   "mark1"
    t.string   "mark2"
    t.string   "mark3"
    t.string   "mark4"
    t.string   "mark5"
    t.string   "mark6"
    t.string   "premark"
    t.integer  "run_id"
    t.datetime "created_at"
    t.integer  "created_by"
    t.datetime "deleted_at"
    t.integer  "deleted_by"
    t.integer  "count"
    t.datetime "since"
    t.datetime "till"
    t.integer  "parent_run_id"
    t.string   "seq"
    t.text     "fullseq",         :limit => 2147483647
    t.integer  "merged_to"
    t.integer  "split_from"
    t.string   "name"
    t.text     "fullname"
    t.text     "fullseq_sub",     :limit => 2147483647
    t.string   "type"
    t.integer  "updated_to"
    t.boolean  "simulation_mode"
  end

  add_index "positions", ["created_by"], :name => "index_positions_on_created_by"
  add_index "positions", ["deleted_by"], :name => "index_positions_on_deleted_by"
  add_index "positions", ["fullseq"], :name => "index_position_on_fullseq"
  add_index "positions", ["run_id"], :name => "index_positions_on_run_id"
  add_index "positions", ["simulation_mode"], :name => "index_positions_on_simulation_mode"
  add_index "positions", ["type"], :name => "index_positions_on_type"
  add_index "positions", ["updated_to"], :name => "index_positions_on_updated_to"

  create_table "questionnaires", :force => true do |t|
    t.integer  "run_id"
    t.datetime "created_at"
    t.integer  "created_by"
    t.datetime "deleted_at"
    t.integer  "deleted_by"
    t.integer  "count"
    t.datetime "since"
    t.datetime "till"
    t.integer  "parent_run_id"
    t.string   "seq"
    t.text     "fullseq",                 :limit => 2147483647
    t.integer  "merged_to"
    t.integer  "split_from"
    t.string   "name"
    t.text     "fullname"
    t.string   "_old_messageID"
    t.string   "_old_rec_seq"
    t.text     "question"
    t.text     "question_type"
    t.string   "necessary"
    t.string   "question_no"
    t.string   "option_count"
    t.string   "correct_ans"
    t.string   "correct_answer_point"
    t.string   "_creater"
    t.integer  "questionnairable_run_id"
    t.text     "fullseq_sub",             :limit => 2147483647
    t.string   "questionnairable_type"
    t.integer  "updated_to"
    t.boolean  "simulation_mode"
  end

  add_index "questionnaires", ["created_by"], :name => "index_questionnaires_on_created_by"
  add_index "questionnaires", ["deleted_by"], :name => "index_questionnaires_on_deleted_by"
  add_index "questionnaires", ["questionnairable_type", "questionnairable_run_id"], :name => "index_questionnaires_on_polymorphic"
  add_index "questionnaires", ["run_id"], :name => "index_questionnaires_on_run_id"
  add_index "questionnaires", ["simulation_mode"], :name => "index_questionnaires_on_simulation_mode"
  add_index "questionnaires", ["updated_to"], :name => "index_questionnaires_on_updated_to"

  create_table "report_comments", :force => true do |t|
    t.integer  "run_id"
    t.datetime "created_at"
    t.integer  "created_by"
    t.datetime "deleted_at"
    t.integer  "deleted_by"
    t.integer  "count"
    t.datetime "since"
    t.datetime "till"
    t.integer  "parent_run_id"
    t.string   "seq"
    t.text     "fullseq",            :limit => 2147483647
    t.integer  "merged_to"
    t.integer  "split_from"
    t.string   "name"
    t.text     "fullname"
    t.string   "_old_report"
    t.integer  "report_run_id"
    t.integer  "report_id"
    t.text     "comment",            :limit => 2147483647
    t.string   "judgement"
    t.string   "_point"
    t.integer  "point"
    t.string   "mark"
    t.string   "_commentator"
    t.integer  "commentator_run_id"
    t.text     "report_tennsaku",    :limit => 2147483647
    t.text     "fullseq_sub",        :limit => 2147483647
    t.integer  "updated_to"
    t.boolean  "simulation_mode"
  end

  add_index "report_comments", ["commentator_run_id"], :name => "index_report_comments_on_commentator_run_id"
  add_index "report_comments", ["created_by"], :name => "index_report_comments_on_created_by"
  add_index "report_comments", ["deleted_by"], :name => "index_report_comments_on_deleted_by"
  add_index "report_comments", ["report_run_id"], :name => "index_report_comments_on_report_run_id"
  add_index "report_comments", ["run_id"], :name => "index_report_comments_on_run_id"
  add_index "report_comments", ["simulation_mode"], :name => "index_report_comments_on_simulation_mode"
  add_index "report_comments", ["updated_to"], :name => "index_report_comments_on_updated_to"

  create_table "reports", :force => true do |t|
    t.string   "_old_student_id"
    t.string   "_old_exe_id"
    t.integer  "exercise_run_id"
    t.string   "title"
    t.text     "body",            :limit => 2147483647
    t.string   "_old_rec_id"
    t.string   "_old_lecture_id"
    t.integer  "run_id"
    t.datetime "created_at"
    t.integer  "created_by"
    t.datetime "deleted_at"
    t.integer  "deleted_by"
    t.integer  "count"
    t.datetime "since"
    t.datetime "till"
    t.integer  "parent_run_id"
    t.string   "seq"
    t.text     "fullseq",         :limit => 2147483647
    t.integer  "merged_to"
    t.integer  "split_from"
    t.string   "name"
    t.text     "fullname"
    t.text     "fullseq_sub",     :limit => 2147483647
    t.integer  "updated_to"
    t.boolean  "simulation_mode"
  end

  add_index "reports", ["created_by"], :name => "index_reports_on_created_by"
  add_index "reports", ["deleted_by"], :name => "index_reports_on_deleted_by"
  add_index "reports", ["exercise_run_id"], :name => "index_reports_on_exercise_run_id"
  add_index "reports", ["run_id"], :name => "index_reports_on_run_id"
  add_index "reports", ["simulation_mode"], :name => "index_reports_on_simulation_mode"
  add_index "reports", ["updated_to"], :name => "index_reports_on_updated_to"

  create_table "semesters", :force => true do |t|
    t.integer  "run_id"
    t.string   "name"
    t.string   "season"
    t.integer  "grade"
    t.integer  "created_by"
    t.integer  "deleted_by"
    t.datetime "created_at"
    t.datetime "since"
    t.datetime "deleted_at"
    t.datetime "till"
    t.string   "seq"
    t.text     "fullseq",         :limit => 2147483647
    t.text     "fullseq_sub",     :limit => 2147483647
    t.string   "fullname"
    t.integer  "merged_to"
    t.integer  "split_from"
    t.integer  "updated_to"
    t.boolean  "simulation_mode"
  end

  add_index "semesters", ["created_by"], :name => "index_semesters_on_created_by"
  add_index "semesters", ["deleted_by"], :name => "index_semesters_on_deleted_by"
  add_index "semesters", ["grade"], :name => "index_semesters_on_grade"
  add_index "semesters", ["name"], :name => "index_semesters_on_name"
  add_index "semesters", ["run_id"], :name => "index_semesters_on_run_id"
  add_index "semesters", ["season"], :name => "index_semesters_on_season"
  add_index "semesters", ["simulation_mode"], :name => "index_semesters_on_simulation_mode"
  add_index "semesters", ["updated_to"], :name => "index_semesters_on_updated_to"

  create_table "seminar_enrollment_schedules", :force => true do |t|
    t.integer  "run_id"
    t.datetime "created_at"
    t.integer  "created_by"
    t.datetime "deleted_at"
    t.integer  "deleted_by"
    t.integer  "count"
    t.datetime "since"
    t.datetime "till"
    t.integer  "parent_run_id"
    t.string   "seq"
    t.text     "fullseq",                  :limit => 2147483647
    t.integer  "merged_to"
    t.integer  "split_from"
    t.string   "name"
    t.text     "fullname"
    t.text     "description"
    t.text     "description_for_teachers"
    t.text     "description_for_students"
    t.text     "fullseq_sub",              :limit => 2147483647
    t.integer  "stage"
    t.datetime "start_time"
    t.datetime "end_time"
    t.integer  "updated_to"
    t.boolean  "simulation_mode"
  end

  add_index "seminar_enrollment_schedules", ["created_by"], :name => "index_seminar_regist_schedules_on_created_by"
  add_index "seminar_enrollment_schedules", ["deleted_by"], :name => "index_seminar_regist_schedules_on_deleted_by"
  add_index "seminar_enrollment_schedules", ["name"], :name => "index_seminar_enrollment_schedules_on_name"
  add_index "seminar_enrollment_schedules", ["run_id"], :name => "index_seminar_regist_schedules_on_run_id"
  add_index "seminar_enrollment_schedules", ["simulation_mode"], :name => "index_seminar_enrollment_schedules_on_simulation_mode"
  add_index "seminar_enrollment_schedules", ["updated_to"], :name => "index_seminar_enrollment_schedules_on_updated_to"

  create_table "seminar_introductions", :force => true do |t|
    t.integer  "run_id"
    t.string   "name"
    t.integer  "created_by"
    t.integer  "deleted_by"
    t.datetime "created_at"
    t.datetime "since"
    t.datetime "deleted_at"
    t.datetime "till"
    t.string   "seq"
    t.text     "fullseq",         :limit => 2147483647
    t.text     "fullseq_sub",     :limit => 2147483647
    t.string   "fullname"
    t.integer  "merged_to"
    t.integer  "split_from"
    t.integer  "updated_to"
    t.boolean  "simulation_mode"
  end

  add_index "seminar_introductions", ["simulation_mode"], :name => "index_seminar_introductions_on_simulation_mode"
  add_index "seminar_introductions", ["updated_to"], :name => "index_seminar_introductions_on_updated_to"

  create_table "seminar_regist_introductions", :force => true do |t|
    t.integer  "run_id"
    t.string   "name"
    t.string   "category"
    t.integer  "created_by"
    t.integer  "deleted_by"
    t.datetime "created_at"
    t.datetime "since"
    t.datetime "deleted_at"
    t.datetime "till"
    t.string   "seq"
    t.text     "fullseq",         :limit => 2147483647
    t.text     "fullseq_sub",     :limit => 2147483647
    t.string   "fullname"
    t.integer  "merged_to"
    t.integer  "split_from"
    t.integer  "updated_to"
    t.boolean  "simulation_mode"
  end

  add_index "seminar_regist_introductions", ["simulation_mode"], :name => "index_seminar_regist_introductions_on_simulation_mode"
  add_index "seminar_regist_introductions", ["updated_to"], :name => "index_seminar_regist_introductions_on_updated_to"

  create_table "seminars", :force => true do |t|
    t.integer  "run_id"
    t.datetime "created_at"
    t.integer  "created_by"
    t.datetime "deleted_at"
    t.integer  "deleted_by"
    t.integer  "count"
    t.datetime "since"
    t.datetime "till"
    t.integer  "parent_run_id"
    t.string   "seq"
    t.text     "fullseq",                            :limit => 2147483647
    t.integer  "merged_to"
    t.integer  "split_from"
    t.string   "name"
    t.text     "fullname"
    t.string   "_section"
    t.string   "_old_rec_id"
    t.integer  "affiliation_run_id"
    t.string   "URL"
    t.text     "body",                               :limit => 2147483647
    t.string   "_created_by"
    t.string   "_teachers"
    t.integer  "students_limit"
    t.string   "year"
    t.text     "fullseq_sub",                        :limit => 2147483647
    t.integer  "seminar_enrollment_schedule_run_id"
    t.boolean  "simulation_mode"
    t.integer  "updated_to"
  end

  add_index "seminars", ["created_by"], :name => "index_seminars_on_created_by"
  add_index "seminars", ["deleted_by"], :name => "index_seminars_on_deleted_by"
  add_index "seminars", ["run_id"], :name => "index_seminars_on_run_id"
  add_index "seminars", ["seminar_enrollment_schedule_run_id"], :name => "index_seminars_on_seminar_enrollment_schedule_run_id"
  add_index "seminars", ["simulation_mode"], :name => "index_seminars_on_simulation_mode"
  add_index "seminars", ["updated_to"], :name => "index_seminars_on_updated_to"

  create_table "stars", :force => true do |t|
    t.integer  "article_run_id"
    t.integer  "user_info_run_id"
    t.integer  "run_id"
    t.datetime "created_at"
    t.integer  "created_by"
    t.text     "create_comment"
    t.datetime "deleted_at"
    t.integer  "deleted_by"
    t.text     "delete_comment"
    t.integer  "version"
    t.integer  "count"
    t.datetime "since"
    t.datetime "till"
    t.integer  "parent_run_id"
    t.integer  "root_run_id"
    t.string   "seq"
    t.text     "fullseq",          :limit => 2147483647
    t.string   "marged_from"
    t.string   "splitted_from"
    t.string   "data_type"
    t.string   "name"
    t.string   "fullname"
    t.text     "fullseq_sub",      :limit => 2147483647
    t.integer  "updated_to"
    t.boolean  "simulation_mode"
  end

  add_index "stars", ["article_run_id", "user_info_run_id"], :name => "index_stars_on_article_run_id_and_user_info_run_id"
  add_index "stars", ["article_run_id"], :name => "index_stars_on_article_run_id"
  add_index "stars", ["created_by"], :name => "index_stars_on_created_by"
  add_index "stars", ["deleted_by"], :name => "index_stars_on_deleted_by"
  add_index "stars", ["name"], :name => "index_stars_on_name"
  add_index "stars", ["run_id"], :name => "index_stars_on_run_id"
  add_index "stars", ["simulation_mode"], :name => "index_stars_on_simulation_mode"
  add_index "stars", ["updated_to"], :name => "index_stars_on_updated_to"
  add_index "stars", ["user_info_run_id"], :name => "index_stars_on_user_info_run_id"

  create_table "syllabus_books", :force => true do |t|
    t.string   "isbn"
    t.string   "isbn10"
    t.string   "isbn13"
    t.integer  "syllabus_run_id"
    t.string   "title"
    t.string   "book_type"
    t.string   "name"
    t.string   "fullname"
    t.integer  "run_id"
    t.integer  "created_by"
    t.integer  "deleted_by"
    t.datetime "created_at"
    t.datetime "since"
    t.datetime "deleted_at"
    t.datetime "till"
    t.string   "seq"
    t.text     "fullseq",         :limit => 2147483647
    t.text     "fullseq_sub",     :limit => 2147483647
    t.integer  "updated_to"
    t.boolean  "simulation_mode"
  end

  add_index "syllabus_books", ["book_type"], :name => "index_syllabus_books_on_book_type"
  add_index "syllabus_books", ["simulation_mode"], :name => "index_syllabus_books_on_simulation_mode"
  add_index "syllabus_books", ["syllabus_run_id"], :name => "index_syllabus_books_on_syllabus_run_id"
  add_index "syllabus_books", ["updated_to"], :name => "index_syllabus_books_on_updated_to"

  create_table "syllabuses", :force => true do |t|
    t.text     "goal",                     :limit => 2147483647
    t.text     "detail",                   :limit => 2147483647
    t.text     "textbook",                 :limit => 2147483647
    t.text     "subtextbook",              :limit => 2147483647
    t.text     "judgment",                 :limit => 2147483647
    t.text     "base_subject",             :limit => 2147483647
    t.text     "relate_subject",           :limit => 2147483647
    t.text     "information",              :limit => 2147483647
    t.text     "old_name",                 :limit => 2147483647
    t.text     "old_name_comment",         :limit => 2147483647
    t.text     "comment",                  :limit => 2147483647
    t.string   "affiliation"
    t.integer  "affiliation_run_id"
    t.string   "affiliation_code"
    t.string   "_old_subject_id"
    t.string   "subject_type"
    t.string   "kei"
    t.string   "gun"
    t.string   "english_name"
    t.string   "_old_name_id"
    t.integer  "previous_syllabus_run_id"
    t.text     "_comment",                 :limit => 2147483647
    t.string   "new_subject_id"
    t.string   "_created_by"
    t.string   "year"
    t.string   "subtitle"
    t.text     "teaching_goal",            :limit => 2147483647
    t.text     "teaching_style",           :limit => 2147483647
    t.text     "question",                 :limit => 2147483647
    t.integer  "run_id"
    t.datetime "created_at"
    t.integer  "created_by"
    t.datetime "deleted_at"
    t.integer  "deleted_by"
    t.integer  "count"
    t.datetime "since"
    t.datetime "till"
    t.integer  "parent_run_id"
    t.string   "seq"
    t.text     "fullseq",                  :limit => 2147483647
    t.integer  "merged_to"
    t.integer  "split_from"
    t.string   "name"
    t.text     "fullname"
    t.text     "fullseq_sub",              :limit => 2147483647
    t.integer  "for_print"
    t.integer  "for_web"
    t.integer  "updated_to"
    t.boolean  "simulation_mode"
  end

  add_index "syllabuses", ["created_by"], :name => "index_syllabuses_on_created_by"
  add_index "syllabuses", ["deleted_by"], :name => "index_syllabuses_on_deleted_by"
  add_index "syllabuses", ["run_id"], :name => "index_syllabuses_on_run_id"
  add_index "syllabuses", ["simulation_mode"], :name => "index_syllabuses_on_simulation_mode"
  add_index "syllabuses", ["updated_to"], :name => "index_syllabuses_on_updated_to"

  create_table "theses", :force => true do |t|
    t.string   "title"
    t.string   "authors"
    t.string   "teacher"
    t.string   "_affiliation"
    t.integer  "affiliation_run_id"
    t.text     "abstract",            :limit => 2147483647
    t.string   "presentation_code"
    t.integer  "presentation_run_id"
    t.time     "start_time"
    t.time     "end_time"
    t.string   "_created_by"
    t.string   "presentation_number"
    t.string   "academic_year"
    t.integer  "run_id"
    t.datetime "created_at"
    t.integer  "created_by"
    t.datetime "deleted_at"
    t.integer  "deleted_by"
    t.integer  "count"
    t.datetime "since"
    t.datetime "till"
    t.integer  "parent_run_id"
    t.string   "seq"
    t.text     "fullseq",             :limit => 2147483647
    t.integer  "merged_to"
    t.integer  "split_from"
    t.string   "name"
    t.text     "fullname"
    t.text     "fullseq_sub",         :limit => 2147483647
    t.string   "type"
    t.integer  "updated_to"
    t.boolean  "simulation_mode"
  end

  add_index "theses", ["academic_year"], :name => "index_theses_on_academic_year"
  add_index "theses", ["created_by"], :name => "index_theses_on_created_by"
  add_index "theses", ["deleted_by"], :name => "index_theses_on_deleted_by"
  add_index "theses", ["presentation_run_id"], :name => "index_theses_on_presentation_run_id"
  add_index "theses", ["run_id"], :name => "index_theses_on_run_id"
  add_index "theses", ["simulation_mode"], :name => "index_theses_on_simulation_mode"
  add_index "theses", ["type"], :name => "index_theses_on_type"
  add_index "theses", ["updated_to"], :name => "index_theses_on_updated_to"

  create_table "thesis_introductions", :force => true do |t|
    t.integer  "run_id"
    t.string   "name"
    t.text     "content",         :limit => 2147483647
    t.integer  "created_by"
    t.integer  "deleted_by"
    t.datetime "created_at"
    t.datetime "since"
    t.datetime "deleted_at"
    t.datetime "till"
    t.string   "seq"
    t.text     "fullseq",         :limit => 2147483647
    t.text     "fullseq_sub",     :limit => 2147483647
    t.string   "fullname"
    t.integer  "merged_to"
    t.integer  "split_from"
    t.integer  "updated_to"
    t.boolean  "simulation_mode"
  end

  add_index "thesis_introductions", ["simulation_mode"], :name => "index_thesis_introductions_on_simulation_mode"
  add_index "thesis_introductions", ["updated_to"], :name => "index_thesis_introductions_on_updated_to"

  create_table "thesis_presentation_schedules", :force => true do |t|
    t.string   "presentation_code"
    t.string   "presentation"
    t.date     "date"
    t.time     "start_time"
    t.string   "place"
    t.string   "academic_year"
    t.integer  "run_id"
    t.datetime "created_at"
    t.integer  "created_by"
    t.datetime "deleted_at"
    t.integer  "deleted_by"
    t.integer  "count"
    t.datetime "since"
    t.datetime "till"
    t.integer  "parent_run_id"
    t.string   "seq"
    t.text     "fullseq",           :limit => 2147483647
    t.integer  "merged_to"
    t.integer  "split_from"
    t.string   "name"
    t.text     "fullname"
    t.string   "thesis_status"
    t.text     "fullseq_sub",       :limit => 2147483647
    t.string   "thesis_degree"
    t.string   "type"
    t.integer  "updated_to"
    t.boolean  "simulation_mode"
  end

  add_index "thesis_presentation_schedules", ["academic_year"], :name => "index_thesis_presentation_schedules_on_academic_year"
  add_index "thesis_presentation_schedules", ["created_by"], :name => "index_thesis_presentation_schedules_on_created_by"
  add_index "thesis_presentation_schedules", ["deleted_by"], :name => "index_thesis_presentation_schedules_on_deleted_by"
  add_index "thesis_presentation_schedules", ["run_id"], :name => "index_thesis_presentation_schedules_on_run_id"
  add_index "thesis_presentation_schedules", ["simulation_mode"], :name => "index_thesis_presentation_schedules_on_simulation_mode"
  add_index "thesis_presentation_schedules", ["type"], :name => "index_thesis_presentation_schedules_on_type"
  add_index "thesis_presentation_schedules", ["updated_to"], :name => "index_thesis_presentation_schedules_on_updated_to"

  create_table "threads", :force => true do |t|
    t.integer  "latest_article_run_id"
    t.integer  "run_id"
    t.datetime "created_at"
    t.integer  "created_by"
    t.text     "create_comment"
    t.datetime "deleted_at"
    t.integer  "deleted_by"
    t.text     "delete_comment"
    t.integer  "version"
    t.integer  "count"
    t.datetime "since"
    t.datetime "till"
    t.integer  "parent_run_id"
    t.integer  "root_run_id"
    t.string   "seq"
    t.text     "fullseq",                :limit => 2147483647
    t.string   "marged_from"
    t.string   "splitted_from"
    t.string   "data_type"
    t.string   "name"
    t.string   "fullname"
    t.text     "fullseq_sub",            :limit => 2147483647
    t.integer  "forum_run_id"
    t.string   "forum_type"
    t.string   "title"
    t.integer  "no_of_articles"
    t.string   "sender_names"
    t.integer  "_latest_article_run_id"
    t.integer  "updated_to"
    t.boolean  "simulation_mode"
  end

  add_index "threads", ["created_by"], :name => "index_threads_on_created_by"
  add_index "threads", ["deleted_by"], :name => "index_threads_on_deleted_by"
  add_index "threads", ["forum_type", "forum_run_id"], :name => "index_threads_on_forum_type_and_forum_run_id"
  add_index "threads", ["latest_article_run_id"], :name => "index_threads_on_latest_article_run_id"
  add_index "threads", ["run_id"], :name => "index_threads_on_run_id"
  add_index "threads", ["simulation_mode"], :name => "index_threads_on_simulation_mode"
  add_index "threads", ["updated_to"], :name => "index_threads_on_updated_to"

  create_table "user_infos", :force => true do |t|
    t.string   "real_name"
    t.string   "name_ruby"
    t.string   "country"
    t.string   "zipcode"
    t.string   "address"
    t.string   "address2"
    t.string   "phone"
    t.string   "fax"
    t.string   "cellular_phone"
    t.string   "email"
    t.string   "room_no"
    t.string   "room_phone"
    t.string   "lab_no"
    t.string   "lab_phone"
    t.string   "url"
    t.text     "description",     :limit => 2147483647
    t.string   "_user_name"
    t.string   "account"
    t.integer  "run_id"
    t.datetime "created_at"
    t.integer  "created_by"
    t.datetime "deleted_at"
    t.integer  "deleted_by"
    t.integer  "count"
    t.datetime "since"
    t.datetime "till"
    t.integer  "parent_run_id"
    t.string   "seq"
    t.text     "fullseq",         :limit => 2147483647
    t.integer  "merged_to"
    t.integer  "split_from"
    t.string   "name"
    t.text     "fullname"
    t.text     "fullseq_sub",     :limit => 2147483647
    t.string   "category"
    t.integer  "updated_to"
    t.boolean  "simulation_mode"
  end

  add_index "user_infos", ["created_by"], :name => "index_user_infos_on_created_by"
  add_index "user_infos", ["deleted_by"], :name => "index_user_infos_on_deleted_by"
  add_index "user_infos", ["run_id"], :name => "index_user_infos_on_run_id"
  add_index "user_infos", ["simulation_mode"], :name => "index_user_infos_on_simulation_mode"
  add_index "user_infos", ["updated_to"], :name => "index_user_infos_on_updated_to"

end
